services:
  db:
    image: postgres:15
    env_file:
      - docker.env
    ports:
      - "5432:5432"
  app:
    build: .
    env_file:
      docker.env
    ports:
      - "8080:8080"
    depends_on:
      db:
        required: true
        condition: service_started
  cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"